apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
  labels:
    name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
